---
- name: Send Hello World Message
  hosts: localhost
  gather_facts: false
    
  tasks:
    - name: Step 1 - Display Hello World
      debug:
        msg: "Hello, World!"
      when: run_step_1
    - name: Step 2 - Display Goodbye World
      debug:
        msg: "Goodbye, World!"
      when: run_step_2
    
